env:
  TERM: "xterm-256color"
  WINIT_HIDPI_FACTOR: "2.25"
  WINIT_X11_SCALE_FACTOR: '1.0'

window:
  opacity: 0.95
  padding:
    x: 5
    y: 5

font:
  normal:
    family: JetBrainsMono Nerd Font
    style: Regular
  bold:
    family: JetBrainsMono Nerd Font
    style: Bold
  italic:
    family: JetBrainsMono Nerd Font
    style: Italic
  bold_italic:
    family: JetBrainsMono Nerd Font
    style: Bold Italic
  size: 14
  offset:
    x: 0
    y: 6

scrolling:
  history: 10000
  multiplier: 100
  faux_multiplier: 100
  auto_scroll: true

draw_bold_text_with_bright_colors: true

# Colors
colors:
  # Default colors
  primary:
    background:        '#011627'
    foreground:        '#acb4c2'
    bright_foreground: '#eeeeee'

  # Cursor colors
  cursor:
    text:   '#080808'
    cursor: '#9ca1aa'

  # Selection colors
  selection:
    text:       '#080808'
    background: '#b2ceee'

  # Normal colors
  normal:
    black:   '#1d3b53'
    red:     '#fc514e'
    green:   '#a1cd5e'
    yellow:  '#e3d18a'
    blue:    '#82aaff'
    magenta: '#c792ea'
    cyan:    '#7fdbca'
    white:   '#a1aab8'

  # Bright colors
  bright:
    black:   '#7c8f8f'
    red:     '#ff5874'
    green:   '#21c7a8'
    yellow:  '#ecc48d'
    blue:    '#82aaff'
    magenta: '#ae81ff'
    cyan:    '#7fdbca'
    white:   '#d6deeb'
